name: manga_reader
description: A manga reading application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0

  cached_network_image: ^3.4.1
  extended_image: ^9.0.2
  photo_view: ^0.15.0

  shared_preferences: ^2.5.4
  path_provider: ^2.1.4
  path: ^1.9.0

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.6

  image_picker: ^1.1.2
  image: ^4.2.0

  flutter_easyloading: ^3.0.5
  file_picker: ^8.1.4
  archive: ^3.6.1
  google_sign_in: ^6.2.2
  googleapis: ^13.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  http: ^1.2.1
  state_notifier: ^1.0.0

  sqflite: any
  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
