dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1

  cached_network_image: ^3.4.1
  extended_image: ^9.0.2
  photo_view: ^0.15.0

  shared_preferences: ^2.3.2
  sqflite: ^2.4.2

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.0 

  image_picker: ^1.2.0
  image: ^4.5.4
